import Head from 'next/head'
import Header from '../components/Header'
import SmallCard from '../components/SmallCard'
import Footer from '../components/Footer'
import CoinsTable from '../components/CoinsTable'

export default function Home() {

  return (
    <div>
      <Head>
        <title>Crypto App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <Header />

      <main className='dark:bg-[#0d1116]'>
        <div>
        <h1 className='tracking-[3px] flex text-center justify-center p-6 text-4xl font-poppins'>Trending <span className='text-[#1850abbf] ml-3 tracking-[3px]'>Coins</span></h1>
        <SmallCard />   
        </div>

        <div>
        <h1 className='tracking-[3px] flex text-center justify-center p-6 text-4xl font-poppins text-purple-400'>All <span className='text-black ml-3 dark:text-white tracking-[3px]'>Coins</span></h1>
          <CoinsTable />
        </div>
      </main>

      <Footer />

    </div>
  )
}